name: DB - Drop Product Tables (Prod)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DELETE" to confirm deletion of Product tables'
        required: true
        type: string

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  SSM_DB_PARAM: /surefilter/DATABASE_URL

jobs:
  drop-tables:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'DELETE'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read DATABASE_URL from SSM
        id: ssm
        run: |
          DB_URL=$(aws ssm get-parameter --with-decryption --name "$SSM_DB_PARAM" --query 'Parameter.Value' --output text)
          if [ -z "$DB_URL" ]; then echo "DATABASE_URL not found in SSM" && exit 1; fi
          # Strip Prisma-specific query params for libpq tools
          DB_URL_PG="${DB_URL%%\?*}"
          echo "db_url_pg=$DB_URL_PG" >> $GITHUB_OUTPUT

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Drop Product tables from production database
        env:
          DATABASE_URL: ${{ steps.ssm.outputs.db_url_pg }}
        run: |
          echo "⚠️  WARNING: Dropping Product, SpecParameter, and ProductSpecValue tables from production database"
          echo "This will delete all product data (currently ~2 products)"
          echo ""
          
          echo "🔍 Checking current Product table counts..."
          psql "$DATABASE_URL" -c "SELECT 'Product' as table_name, COUNT(*) as count FROM \"Product\" 
                   UNION ALL SELECT 'SpecParameter', COUNT(*) FROM \"SpecParameter\" 
                   UNION ALL SELECT 'ProductSpecValue', COUNT(*) FROM \"ProductSpecValue\";" || echo "Tables don't exist yet"
          
          echo ""
          echo "🗑️  Dropping tables..."
          psql "$DATABASE_URL" -c "DROP TABLE IF EXISTS \"ProductSpecValue\" CASCADE;"
          psql "$DATABASE_URL" -c "DROP TABLE IF EXISTS \"Product\" CASCADE;"
          psql "$DATABASE_URL" -c "DROP TABLE IF EXISTS \"SpecParameter\" CASCADE;"
          
          echo ""
          echo "✅ Product tables dropped successfully!"
          echo ""
          echo "📋 Next steps:"
          echo "1. Run the 'DB - Prisma Migrate Deploy' workflow to apply the new migration"
          echo "2. The migration will recreate these tables with proper migration tracking"

      - name: Verify tables are dropped
        env:
          DATABASE_URL: ${{ steps.ssm.outputs.db_url_pg }}
        run: |
          echo "🔍 Verifying tables are dropped..."
          TABLE_COUNT=$(psql "$DATABASE_URL" -t -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('Product', 'SpecParameter', 'ProductSpecValue');")
          
          if [ "$TABLE_COUNT" -eq 0 ]; then
            echo "✅ All Product tables have been dropped successfully"
          else
            echo "❌ Some tables still exist (found: $TABLE_COUNT)"
            exit 1
          fi

