name: Static - Upload to S3

on:
  workflow_dispatch:
    inputs:
      bucket:
        description: "S3 bucket name (e.g. surefilter-static-prod)"
        required: false
        default: "surefilter-static-prod"
      invalidate:
        description: "Invalidate CloudFront paths after upload"
        required: false
        default: "false"

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Next.js
        working-directory: surefilter-ui
        run: |
          npm ci
          npm run build

      - name: Upload _next/static
        run: |
          aws s3 sync surefilter-ui/.next/static s3://${{ github.event.inputs.bucket || 'surefilter-static-prod' }}/_next/static/ \
            --cache-control "public,max-age=31536000,immutable" --delete

      - name: Upload public/images
        run: |
          if [ -d surefilter-ui/public/images ]; then \
            aws s3 sync surefilter-ui/public/images s3://${{ github.event.inputs.bucket || 'surefilter-static-prod' }}/images/ \
              --cache-control "public,max-age=31536000,immutable" --delete; \
          fi

      - name: Invalidate CloudFront paths (optional)
        if: ${{ github.event.inputs.invalidate == 'true' }}
        run: |
          DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='surefilter new.surefilter.us'].Id" --output text)
          aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/_next/static/*" "/images/*"


